### ISSUE TITLE
More non spring examples + proper docs + bunch of questions

### ISSUE THREAD

**Issue by RIP21** [apollographql/federation-jvm#17]
Hi there.
I understand how Spring Boot and Spring itself is beneficial (especially for microservices), but I really want to see pure implementation with 2-3 different federated services written in `graphql-java` and `apollo-server` that sticks it all as a whole thing using a gateway.

Another question is, will Apollo Engine work with those `graphql-java` federated services, or they will be a bunch of black boxes until proper `apollo-engine` instrumentation is implemented? (I mean resolvers tracing and all advanced, not static schema related stuff)

If they indeed will, is Apollo has any plans to implement some sort of library that will help with instrumentation of `graphql-java` based GraphQL Servers? It's kind of roadblock for us to start to consider it at Revolut. 

(we have all backend in Java/Kotlin and we're moving heavily towards microservices, Node.js is not an option with that amount of JVM devs, and I'm as an evangelist of GQL in the company, want to make sure everything is there for GraphQL in JVM world, to start promoting it heavily or even build a prototype for them, also, Spring is forbidden in our company, that's why I'm looking for Spring agnostic implementation)

**Comment by glasser** [comment]
See #25 for federated tracing support.

**Comment by zionts** [comment]
I'm going to close this out in favor of #16 , which calls for a clearer roadmap and some more information about the project, release notes, etc. 

We know that there is a big gap in the documentation for this library as well as expectations for the community, and I'm sorry it's taken this long to get back to you with clear communication. This library was originally started as a way to support _our own_ Kotlin services in the Apollo back-end, and we haven't been as proactive as we would have liked as an open source project. We would welcome more partnership in open source maintenance if you're interested!

To respond to your specific comments about this library, though: this library is recommended for production GraphQL services underneath an Apollo gateway and is currently used in production by both ourselves at Apollo as well as other Apollo gateway users. Additionally, we don't use Spring internally with this implementation and we only illustrated it in the example because of its popularity. Perhaps an implementation with ktor (what we use internally) would be a useful example to share?

**Comment by rkudryashov** [comment]
@zionts yes, it would be nice to have example of using the library on any framework (something like https://github.com/apollographql/federation-demo).
