### ISSUE TITLE
graphql-java-support: Bump graphql-java to v18.1

### ISSUE THREAD

**Issue by LizGabriela-RY** [apollographql/federation-jvm#170]
It is any plan to add support/compatibility with graphql-java v.18.1? Any alpha version where this is been considered?

**Comment by martinbonnin** [comment]
Sure! Is there anything in particular you're interested in v18? It might already work if you pin your `graphql-java` version

**Comment by martinbonnin** [comment]
Can you share what the stacktrace/error is?

**Comment by LizGabriela-RY** [comment]
The error found is in the federation test level:
-------------------------------------------------------------------------------
graphql.schema.validation.InvalidSchemaException: invalid schema:
A definition for directive 'key' could not be found
-------------------------------------------------------------------------------
I can share the complete trace and unit test tomorrow. This is thrown at the SchemaTransformer level.

**Comment by martinbonnin** [comment]
Interesting. Yep, I would have expected the `@key` directive to be added automatically. A unit test would be welcome. We're due to release tomorrow so (unless there are some unforeseen complications) we'll bump to v18 but it might also be something else so any unit test/reproducer would be very welcome 👍

**Comment by martinbonnin** [comment]
I gave it a quick look today and "it's complicated". Upgrading itself is working but fails in `spring-sample` because the sample is using `graphql-java-tools` and that's not compatible with `graphql-java` 18 just yet. We could think of ways to work around this but that's a longuer story so not for today.

In all cases, please send a reproducer as your issue might still have another solution

**Comment by LizGabriela-RY** [comment]
Hey! Thank you so much for your comments, actually, after reviewing in detail it has been found an solution similar to what is proposed here: https://github.com/apollographql/federation-jvm/issues/35 so we are good with the tests now. Anyway, I would be looking forward to the new release & features to try. Hopefully, all goes well with the release today! :)

**Comment by setchy** [comment]
@martinbonnin - I noticed earlier today that the [graphql-java-tools:12.1.0 release](https://github.com/graphql-java-kickstart/graphql-java-tools/releases/tag/v12.1.0) now uses `graphql-java:18.1`.  kickstart however is pending a release (shortly) to update to use the new `graphql-java-tools`

**Comment by setchy** [comment]
#196
