### ISSUE TITLE
Remove Subscription type and custom directives from sdl

### ISSUE THREAD

**Issue by elxnis** [apollographql/federation-jvm#35]
Hi,

Gateway is freaking out if there is Subscription type or custom directives in sdl response, so they should be filtered out.

I don't have time to create proper PR, but it could look something like this if someone wants to try it.

com.apollographql.federation.graphqljava.SchemaTransformer

```
public final GraphQLSchema build() throws SchemaProblem {
//... unchanged
final GraphQLSchema sdlSchema = GraphQLSchema.newSchema()
        .query(originalSchema.getQueryType())
        .additionalTypes(originalSchema.getAdditionalTypes())
        .codeRegistry(originalSchema.getCodeRegistry())
        .build(); // create copy of original schema but remove subscription type
        final String sdl = sdl(sdlSchema);
//... unchanged
}
```

```
private String sdl(final GraphQLSchema schema) {
    final SchemaPrinter.Options options = SchemaPrinter.Options.defaultOptions()
        .includeScalarTypes(true)
        .includeExtendedScalarTypes(true)
        .includeSchemaDefintion(false)
        .includeDirectives(true);

    // use regex to cut out custom directives from sdl 
    return new SchemaPrinter(options).print(schema)
        .replaceAll("\\s?@\\b(?!(extends|external|key|provides|requires|deprecated)\\b)\\w+(?:\\s*\\(.*?\\))?", "");
  }
```

Thanks,
Reinis

**Comment by zionts** [comment]
It sounds like you're trying to work around a limitation in Apollo gateway where custom directives and the existence of the Subscription type cause errors to be thrown. Rather than introducing a feature to this library that works around this gateway limitation (and thereby removes the functionality that you're trying to expose), I think this conversation should be escalated to the [apollo-server 3.0 Roadamp](https://github.com/apollographql/apollo-server/issues/2360), where I _believe_ support for both features you discuss are being addressed. I'm going to close this out for now, but if I've misunderstood your use case or request, feel free to reopen and explain a bit further what it is you're looking for :)

**Comment by elxnis** [comment]
As it stands currently gateway can't do anything with custom directives and Subscription type, so it might make sense that they don't expect them being present on _service.sdl field. I agree that they should handle it gracefully and probably remove it on their side, but they might just to extend spec to say that _service.sdl shouldn't contain them (I remember seeing this somewhere, but can't find it anymore, but I see this https://www.apollographql.com/docs/apollo-server/federation/implementing/#implementing-custom-directives where it states that the same directives have to be on all servers.

My suggestion doesn't remove this functionally from graphql-java server as it just removes it from printed sdl schema on _service.sdl field. We could also achieve this by allowing to define custom DataFetcher for sdl field instead of relying on SchemaTransformer to create it (can keep it us default behaviour). This would also allow to expose subset of schema to gateway.

**Comment by elxnis** [comment]
@zionts I am not able to re-open this issue as it wasn't closed by me.

**Comment by ilinoyer** [comment]
We have a similar issue in our project. We want to start the migration from one big GraphQL API to federation but gateway fails when sdl response contains custom directives. In our case, we don`t need these directives on the gateway level but now there is no possibility to remove it from fetcher in a clean way. I can imagine it is not a problem when you start from federations because you are aware of current gateway limitations but for us is blocking issue. Maybe we can discuss some possibilities and reopen this issue?
