### ISSUE TITLE
how can i use union type？

### ISSUE THREAD

**Issue by xiaoyx1994** [apollographql/federation-jvm#59]
How can I use union type?
Please provider a demo to springboot example.
Think you!

**Comment by sachindshinde** [comment]
@xiaoyx1994 You can use GraphQL union types in Apollo Federation as you normally would in a non-Federation context (although you can't have a union type as a Federation entity, since there would be no field to use with an `@key` directive). Is there a specific way you'd like to use unions in Federation that's confusing/not working for you?

**Comment by xiaoyx1994** [comment]
@sachindshinde thank you!
