### ISSUE TITLE
Remove Subscription type and custom directives from printed sdl 

### ISSUE THREAD

**Issue by elxnis** [apollographql/federation-jvm#64]
This is follow up for the issue I have raised before #35 

Some things have changed in library, so I am raising this again.

We are still using custom implementation of federation support as this is not working for us.

apollo-gateway doesn't support Subscriptions and even if it did it probably won't match our transfer mechanism for it, so it should be removed from printed sdl. We still want to support Subscriptions on individual graphql servers, but currently not on gateway.

Similarly printed sdl includes custom directive definitions and directives themselves, but they are not really useful for gateway as well, so they should be removed from printed sdl as well. Similarly you can argue that it might be similar how introspection is not showing where directives are applied, but in this case we still need federation directives to be present on printed sdl.

The new **FederationSdlPrinter** has a lot of options to control some of these things, but there is no way to pass them as **SchemaTransformer** just sets them up.

Currently **Federation** and **SchemaTransformer** are really restricted where users don't have many options and I would like to change it to allow passing FederationSdlPrinter.Options and include new options to control what schema root types (Query, Subscription, Mutation) needs printed.

I am happy to raise PR for both of the issues, but I just wanted to know what are your thoughts on this before I spend more time on this as my previous issue was just closed.

**Comment by dariuszkuc** [comment]
SDL printer changed a lot since 2020, fed v1 required all custom directives to be stripped out but this is no longer the case in fed v2. Custom schema transformation can still be applied after running the `Federation/SchemaTransformer` logic.

Starting with Federation v2.1 you can use [`@composeDirective`](https://www.apollographql.com/docs/federation/federated-types/federated-directives#composedirective) to preserve custom directive in the supergraph schema and starting with [Federation v2.4](https://www.apollographql.com/docs/federation/federation-versions#v24) subscriptions are supported as well.

If this is still an issue please open up a new one.
