### ISSUE TITLE
Question to the SchemaTransformer logic

### ISSUE THREAD

**Issue by rstep** [apollographql/federation-jvm#70]
Hello, just wonder if you can help me understand the logic behind the following requirement:
```
If your schema does not contain any types annotated with the @key directive, nothing else is required. You can build a transformed GraphQLSchema with SchemaTransformer#build(), and confirm it exposes query { _schema { sdl } }.

Otherwise, all types annotated with @key will be part of the _Entity union type, and reachable through query { _entities(representations: [Any!]!) { … } }
```

According to the [specification](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/), if I extend another type I have to add **@key** directive. But in case if I just want to reference another type and I don't extend it with any additional attributes, why do I have to define data fetcher that will never be invoked? 

Moreover, I've just looked through the code of SchemaTransformer.java, and it doesn't validate that particular type with directive @key defined has data fetcher, it is enough if there is at least one defined.

This looks like something that need to be changed.

**Comment by setchy** [comment]
Likewise @sachindshinde - not sure if the latest updates made under #101 allow this to be closed

**Comment by dariuszkuc** [comment]
Hello 👋 

>But in case if I just want to reference another type and I don't extend it with any additional attributes, why do I have to define data fetcher that will never be invoked?

This was addressed in Federation v2 -> if you just need to reference entity now you can specify `resolvable: false` on the `@key` directive. This will ensure that the router/gateway will not attempt to resolve the type in the given subgraph and always make federated call.

I've updated the logic in https://github.com/apollographql/federation-jvm/pull/285 to also auto populate `_Entity` union type resolver with a fake one (that throws runtime exception if invoked -> it should never be invoked, if for some reason it is, e.g. due to local testing, your provided resolver takes precedence) and no longer require `_entities` resolver if all entities are non-resolvable.
