### ISSUE TITLE
publish to MavenCentral

### ISSUE THREAD

**Issue by dariuszkuc** [apollographql/federation-jvm#91]
Currently this project is published only to JCenter. With the announcement that JCenter is going to be sunset on May 1st 2021 are there any plans to migrate to MavenCentral instead?

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by smyrick** [comment]
The other important date is Feb 28th when we will no longer be able to publish new versions there. So it really should happen before then incase a bug fix needs to go out

**Comment by sachindshinde** [comment]
Yep, we'll be migrating this project to MavenCentral before Feb 28th.

**Comment by Moltik** [comment]
Hi guys. Any news on migration?

**Comment by sachindshinde** [comment]
@Moltik Changing the project to deploy to Maven Central should be straightforward (add GPG signing + switch deploy plugins), but moving old artifacts will be more painful since our POMs currently fail [Maven Central POM validation](https://central.sonatype.org/pages/requirements.html). The current plan is to repackage old releases with valid POMs and re-release to Maven Central, which will involve backporting some changes to every release branch (we'll do some testing here with the re-releases on our own infra).

**Comment by Moltik** [comment]
Got it. Thank you. Is there any hope that the migration will end before February 28?

**Comment by paulbakker** [comment]
@Moltik Although I hope this library will be pushed to central soon anyway, the February 28 deadline isn't so much the deadline anymore. From the [bintray website](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/): 

```UPDATE: To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st 2021.

To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021.```

**Comment by sachindshinde** [comment]
@Moltik We expect to get this repo publishing new packages to Maven Central by Feb 28th (and to publish a new package to Maven Central by Feb 28th, which we'll test in our infra).

Moving old artifacts will take longer; generally, we'd like to use a method that avoids recompiling and just updates the POM with the metadata changes needed, recomputes MD5s, resigns, and uploads. We know of scripts that have been recently developed to do this, but we'll need to evaluate whether they'll require any changes to work with this repo.

Thankfully JCenter will continue to host artifacts for another year, so this isn't as pressing (but we'd still like to get this done soon so that users don't find themselves depending on JCenter as the deadline approaches).

@paulbakker That's good news about the postponement of the Feb 28th deadline regarding new package version submissions. We still intend to get publishing to Maven Central by Feb 28th, but the extension from them is appreciated.

**Comment by dariuszkuc** [comment]
@sachindshinde Feb 28th is the deadline for new publishing new libs, May 1st is the deprecation of the REST APIs and UI, artifact resolution (through Maven and Gradle) will work through Feb next year.

**Comment by sachindshinde** [comment]
@dariuszkuc It looks like the timeline has been altered slightly, based on the [current version of the blogpost](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/):
<img width="882" alt="Bintray Timeline" src="https://user-images.githubusercontent.com/2695578/109199357-3419db00-7754-11eb-877c-e200785c798d.png">

Regardless, we still intend to start publishing to Maven Central by Feb 28th, and to move old artifacts over shortly after once we've found/developed a script that works for this repo.

**Comment by sachindshinde** [comment]
@dariuszkuc @smyrick @Moltik @paulbakker 
This project now publishes to Maven Central instead of JCenter. The first release on Maven Central is v0.6.3, for those interested in having one less dependency on JCenter.

**Comment by paulbakker** [comment]
This is great, thanks for getting it done!

**Comment by abernix** [comment]
Closing, as this was completed.  Thanks for getting this done, @sachindshinde !

**Comment by dariuszkuc** [comment]
Only latest version 0.6.3 is available on Maven Central - are older versions still going to be published?
